let products = [
    {
        "id": 1001,
        "title": "Math",
        "description": "Mathematics is a crucial subject to everyday life and academic success , which students will continue through each grade of their school journey.",
        "price": 400,
        "location": "Santa Monica",
        "image": "images/product-math.png",
        "availableInventory": 5, 
        "rating": 5,
    },
    {
        "id": 1002,
        "title": "English",
        "description": "English is spoken in every country, it is cool to learn as a primary language and even cooler for a Secondary Language.",
        "price": 350,
        "location": "Arizona",
        "image": "images/product-english.jpg",
        "availableInventory": 5, 
        "rating": 5,
    },
    {
        "id": 1003,
        "title": "Basketball",
        "description": "We will to teach the fundamentals  of basketball and discipline to push you to the best of your ability , and also help you go pro.",
        "price": 250,
        "location": "Texas",
        "image": "images/product-basketball.jpg",
        "availableInventory": 5, 
        "rating": 3,
    },
    {
        "id": 1004,
        "title": "Football",
        "description":  "We Teach You Football The Right Way.",
        "price": 200,
        "location": "Colorado",
        "image": "images/product-Soccer.jpg",
        "availableInventory": 5, 
        "rating": 5,
    },
    {
        "id": 1005,
        "title": "Tennis",
        "description":"Tennis brings a different vibe to the body and soul,come enjoy and explore the world of tennis.",
        "price": 150,
        "location": "San fransisco",
        "image": "images/product-tennis.jpg",
        "availableInventory": 5, 
        "rating": 4,
    },
    {
        "id": 1006,
        "title": "E-Sports",
        "description": "With Esports being one of the fastest growing markets in the world right now, let us set you on the path to Esports Greatness.",
        "price": 500,
        "location": "San fransisco",
        "image": "images/product-apex.jpg",
        "availableInventory": 5, 
        "rating": 5,
    },
    {
        "id": 1007,
        "title": "Geography",
        "description": "Geography is the study of the Earth's physical features and environment including the impact of human activity on these factors and vice versa.",
        "price": 200,
        "location": "Arizona",
        "image": "images/product-geo.png",
        "availableInventory": 5, 
        "rating": 4,
    },
    {
        "id": 1008,
        "title": "French",
        "description": "Learning extra languages is  very essential, french is one language you will love to learn , join us as we bring france to you.",
        "price": 600,
        "location": "Buffalo",
        "image": "images/product-french.png",
        "availableInventory": 5, 
        "rating": 3,
    },
    {
        "id": 1009,
        "title": "Swimming",
        "description": "Swimming is an essential skill for human survival , alongside Very Relaxing properties and Physical conditioning .",
        "price": 250,
        "location": "Washington",
        "image": "images/product-swim.jpg",
        "availableInventory": 5, 
        "rating": 3,
    },
    {
        "id": 1010,
        "title": "Judo",
        "description": "The art of Judo is a very lovely skill to harness, Let's put you through from beginner to expert level and you can compete anywhere.",
        "price": 145,
        "location": "New York",
        "image": "images/product-judo.jpg",
        "availableInventory": 5, 
        "rating": 5,
    },
]